# This dockerfile serves as a base for all testing images.
# It contains the minimal dependencies and is therefore smaller.
FROM registry.risc-software.at/common/ci-templates/python/pyenv:latest

ARG PYTHON_VERSION={{cookiecutter.python_version}}
ARG POETRY_VERSION=1.5.1
LABEL maintainer="{{cookiecutter.author_name}} <{{cookiecutter.author_email}}>"

RUN pip install --upgrade pip

# Install python and set interpreter
RUN pyenv install -s ${PYTHON_VERSION} && pyenv global ${PYTHON_VERSION}

# Install and configure Poetry
ENV POETRY_VERSION=${POETRY_VERSION} \
    POETRY_HOME=/opt/poetry \
    POETRY_VIRTUALENVS_CREATE=false
RUN curl -sSL https://install.python-poetry.org | python -
ENV PATH="${PATH}:${POETRY_HOME}/bin"

# Setup directory structure
RUN mkdir /repo
WORKDIR /repo

# Install dependencies (package itself is not installed)
COPY pyproject.toml poetry.lock .
RUN poetry install --without dev --all-extras --no-root

# Copy the rest of the repository
ADD . .
