[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{{ cookiecutter.__package_name_kebab_case }}"
version = "0.0.1"
requires-python = "~={{ cookiecutter.python_version }}.0"
description = "{{ cookiecutter.package_description }}"
authors = [{ name = "{{ cookiecutter.author_name }}", email = "{{ cookiecutter.author_email }}" }]
readme = "README.md"
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
  # "torch>=2.10.0,<2.11.0",
]

[project.urls]
Repository = "{{ cookiecutter.package_url }}"

[tool.uv]
environments = ["python_version == '{{ cookiecutter.python_version }}'"]
# Uncomment to exclude unwanted transitive dependencies
# exclude-dependencies = ["opencv-python"]

[[tool.uv.index]]
name = "risc-pypi"
url = "https://pypinexus01.risc-software.at/repository/pypi/simple/"
explicit = true
{% if cookiecutter.gpu_support %}
[[tool.uv.index]]
# The cuda version specified here must match the one of `FROM_IMAGE` specified in `.devcontainer/docker-compose.yml`.
name = "pytorch-cu129"
url = "https://download.pytorch.org/whl/cu129"
explicit = true

[tool.uv.sources]
# The cuda version specified here must match the one of `FROM_IMAGE` specified in `.devcontainer/docker-compose.yml`.
torch = [
  {index = "pytorch-cu129", marker = "sys_platform == 'linux' or sys_platform == 'win32'"},
]
torchvision = [
  {index = "pytorch-cu129", marker = "sys_platform == 'linux' or sys_platform == 'win32'"},
]
{%- else %}
# Uncomment for GPU support:
# [[tool.uv.index]]
# # The cuda version specified here must match the one of `FROM_IMAGE` specified in `.devcontainer/docker-compose.yml`.
# name = "pytorch-cu129"
# url = "https://download.pytorch.org/whl/cu129"
# explicit = true
#
# [tool.uv.sources]
# # The cuda version specified here must match the one of `FROM_IMAGE` specified in `.devcontainer/docker-compose.yml`.
# torch = [
#   {index = "pytorch-cu129", marker = "sys_platform == 'linux' or sys_platform == 'win32'"},
# ]
# torchvision = [
#   {index = "pytorch-cu129", marker = "sys_platform == 'linux' or sys_platform == 'win32'"},
# ]
{%- endif %}

[tool.hatch.build.targets.sdist]
include = ["{{ cookiecutter.__package_name_snake_case }}"]

[tool.hatch.build.targets.wheel]
include = ["{{ cookiecutter.__package_name_snake_case }}"]

[dependency-groups]
dev = [
  "black[jupyter]>=26.1.0",
  "isort>=7.0.0",
  "liccheck>=0.9.2",
  "mkdocs>=1.6.1",
  "mkdocs-material>=9.7.1",
  "mkdocstrings[python]>=1.0.3",
  "pip>=26.0.1",
  "poethepoet>=0.41.0",
  "pytest>=9.0.2",
  "pytest-clarity>=1.0.1",
  "pytest-cov>=7.0.0",
  "pytest-xdist>=3.8.0",
  "ruff>=0.15.0",
  
  # pinned for liccheck
  "setuptools==78.1.0",
]

[tool.poe.tasks]
# https://github.com/nat-n/poethepoet
_format = "black ."
_sort_imports = "isort ."
_lint = "ruff check --fix ."

_check_format = "black --check ."
_check_sort_imports = "isort --check ."
_check_lint = "ruff check ."

# if you are using uv for dependency management, you have to generate a requirements.txt first
_convert_to_req_txt = { shell = "uv export --no-hashes --format=requirements-txt > requirements.txt" }
# check authorization of the licenses of dependencies as defined in [tool.liccheck] section 
# (or a separate liccheck.ini-file)
_check_licenses = "liccheck -s liccheck.ini -r requirements.txt"

check_licenses = [
    "_convert_to_req_txt",
    "_check_licenses",
]

docs = "mkdocs serve"
precommit = ["_format", "_sort_imports", "_lint"]
check = ["_check_format", "_check_sort_imports", "_check_lint", "check_licenses"]
test = "pytest"
{% if cookiecutter.gpu_support %}
smi = "nvidia-smi"
check_torch = """
python -c 'import torch; 

# Fail fast
assert torch.cuda.is_available(), "CUDA not available";

# Info
print(f\"PyTorch version: {torch.__version__}\"); 
print(f\"CUDA available: {torch.cuda.is_available()}\"); 
print(f\"CUDA version: {torch.version.cuda}\"); 
print(f\"GPU device: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'None'}\")

# Smoke test
torch.randn(1024,1024,device="cuda");
torch.cuda.synchronize();'
"""
check_cuda = ["smi", "check_torch"]
{%- else %}
# Uncomment for GPU debugging:
# smi = "nvidia-smi"
# check_torch = """
# python -c 'import torch; 
#
# # Fail fast
# assert torch.cuda.is_available(), "CUDA not available";
#
# # Info
# print(f\"PyTorch version: {torch.__version__}\"); 
# print(f\"CUDA available: {torch.cuda.is_available()}\"); 
# print(f\"CUDA version: {torch.version.cuda}\"); 
# print(f\"GPU device: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'None'}\")
#
# Smoke test
#torch.randn(1024,1024,device="cuda");
#torch.cuda.synchronize();'
# """
# check_cuda = ["smi", "check_torch"]
{%- endif %}

[tool.black]
# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file
line-length = 120

[tool.isort]
# https://pycqa.github.io/isort/docs/configuration/config_files
profile = "black"

[tool.pytest.ini_options]
# https://docs.pytest.org/en/7.1.x/reference/customize.html
addopts = "--color=yes --doctest-modules  -ra --cov --cov-report=html --cov-report term --cov-report xml:coverage.xml --exitfirst --failed-first --strict-config --strict-markers --verbosity=2 --junitxml=python-junit.xml"
xfail_strict = true
pythonpath = ["{{ cookiecutter.__package_name_snake_case }}"]
testpaths = ["{{ cookiecutter.__package_name_snake_case }}", "tests"]
# ignore any of these paths
norecursedirs = [ ]

[tool.ruff]
# https://github.com/charliermarsh/ruff
fix = true
line-length = 120
src = ["{{ cookiecutter.__package_name_snake_case }}", "tests"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 120

[tool.ruff.lint.pydocstyle]
convention = "{{ cookiecutter.docstring_style|lower }}"

[tool.liccheck]
# see also: https://pypi.org/project/liccheck/
# Authorized and unauthorized licenses in LOWER CASE
authorized_licenses = [
  "bsd",
  "new bsd",
  "bsd-2-clause",
  "bsd 2-clause",
  "bsd-3-clause",
  "bsd 3-clause",
  "bsd license",
  "isc",
  "isc license",
  "isc license (iscl)",
  "apache",
  "apache-2.0",
  "apache 2.0",
  "apache software",
  "apache software license",
  "apache license, version 2.0",
  "gnu lgpl",
  "historical permission notice and disclaimer (hpnd)",
  "lgpl with exceptions or zpl",
  "mozilla public license 2.0 (mpl 2.0)",
  "mit",
  "mit license",
  "new bsd license",
  "python software foundation license",
  "python software foundation",
  "psf-2.0",
  "simplified bsd",
  "the unlicense (unlicense)",
]
# as_regex = true -> e.g. '\bgpl'
unauthorized_licenses = [
  "gpl v3",
  "gnu general public license v2 or later (gplv2+)",
]
level = "standard"  # alternatives: "cautious", "paranoid"
requirement_txt_file = "./requirements.txt"
reporting_txt_file = "./liccheck_reporting.txt" # by default is None

# 'uv export' already unrolls transitive deps into requirements.txt
# therefore another resolution is not needed
# this even hindered the usage of 'exclude-dependencies'
no_deps = true

[tool.liccheck.authorized_packages]
# Python software license (see http://zesty.ca/python/uuid.README.txt)
uuid = "1.30"
